### ISSUE TITLE
Babel cannot find module `../modules/web.dom.iterable` when trying to build

### ISSUE THREAD

**Issue by schas002** [tuxcrafting/your-mom#3]
A bash log is worth 1024 words:

```
schas002:~/workspace (master) $ npm install && npm run build

> your-mom@1.0.0 build /home/ubuntu/workspace
> babel src -d lib

Error: Cannot find module '../modules/web.dom.iterable'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/workspace/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-template-literals/node_modules/babel-runtime/node_modules/core-js/library/fn/get-iterator.js:1:63)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

npm ERR! Linux 4.2.0-c9
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v4.4.5/bin/node" "/home/ubuntu/.nvm/versions/node/v4.4.5/bin/npm" "run" "build"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code ELIFECYCLE
npm ERR! your-mom@1.0.0 build: `babel src -d lib`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the your-mom@1.0.0 build script 'babel src -d lib'.
npm ERR! This is most likely a problem with the your-mom package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel src -d lib
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs your-mom
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls your-mom
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/workspace/npm-debug.log
```

**Comment by vihanb** [comment]
@tuxcrafting use `./node_modules/.bin/babel` rather than `babel` itself as `npm install` doesn't install globally

**Comment by tuxcrafting** [comment]
@vihanb Thank you

**Comment by schas002** [comment]
Fixed in 371647b171d44e573ab0ec3100b65f6f6e703526

**Comment by schas002** [comment]
Fix invalid, evidence:

```
schas002:~/workspace (master) $ npm install && npm run build
readline-sync@1.4.4 node_modules/readline-sync

> your-mom@1.0.0 build /home/ubuntu/workspace
> babel src -d lib

Error: Cannot find module '../modules/web.dom.iterable'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/workspace/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-template-literals/node_modules/babel-runtime/node_modules/core-js/library/fn/get-iterator.js:1:63)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

npm ERR! Linux 4.2.0-c9
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v4.4.5/bin/node" "/home/ubuntu/.nvm/versions/node/v4.4.5/bin/npm" "run" "build"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code ELIFECYCLE
npm ERR! your-mom@1.0.0 build: `babel src -d lib`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the your-mom@1.0.0 build script 'babel src -d lib'.
npm ERR! This is most likely a problem with the your-mom package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel src -d lib
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs your-mom
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls your-mom
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/workspace/npm-debug.log
```

**Comment by schas002** [comment]
[The developers] had [one job]... :angry:

**Comment by vihanb** [comment]
Same bug, @tuxcrafting didn't fix it everywhere

**Comment by vihanb** [comment]
@schas002 this bug is your fault. Did you fully reinstall?

**Comment by schas002** [comment]
Nope, but I found a temporary work around.

As specified in the README, you need to run `src/yourmom.js` directly.

**Comment by vihanb** [comment]
._. Wait, so you didn't reinstall but you're saying the bug is still happening? wat
